linkedin/Hoptimator

Makefile, deploy/kafkatopics.crd.yaml, deploy/samples/kafkatopic.yaml, deploy/samples/subscription.yaml, deploy/samples/subscriptions.yaml, deploy/subscriptions.crd.yaml, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/AvroConverter.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Resource.java, hoptimator-cli/src/main/java/com/linkedin/hoptimator/HoptimatorCliApp.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/KafkaTopic.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/RawKafkaSchemaFactory.java, hoptimator-kafka-adapter/src/main/resources/KafkaTopic.yaml.template, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/Operator.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/kafka/KafkaTopicReconciler.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopic.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicList.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpec.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecClientConfigs.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecConfigMapRef.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicStatus.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SqlJob.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SqlJobList.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SqlJobSpec.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SqlJobStatus.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Subscription.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionList.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionSpec.java, models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionStatus.java
Validated that resources can be shared between multiple subscriptions.
Deployed a subscription `names` which joins the output of two other subscriptions:
```
$ kubectl get subscriptions
NAME        DB         SQL
companies   RAWKAFKA   SELECT NAME FROM DATAGEN.COMPANY
names       RAWKAFKA   SELECT p.PAYLOAD || c.PAYLOAD FROM RAWKAFKA."people" p, RAWKAFKA."companies" c
people      RAWKAFKA   SELECT NAME FROM DATAGEN.PERSON
```
The subscription takes ownership of the two source Kafka topics, as well as the new sink Kafka topic:
```
$ kubectl tree subscription names
NAMESPACE  NAME                                                    READY  REASON  AGE
default    Subscription/names                                      -              63m
default    ├─KafkaTopic/companies-kafka-topic …
```
=> Fix multiple owner references

Makefile
Integration tests failed a few times due to CRDs being Created but not yet Established. For the resources not managed by Helm, I've added `kubectl wait`s to ensure this no longer happens. (At least for the CRDs we know about so far.)
```
--->%---
customresourcedefinition.apiextensions.k8s.io/subscriptions.hoptimator.linkedin.com configured
kubectl wait --for=condition=Established=True	\
crds/subscriptions.hoptimator.linkedin.com \
crds/kafkatopics.hoptimator.linkedin.com \
crds/sqljobs.hoptimator.linkedin.com
customresourcedefinition.apiextensions.k8s.io/subscriptions.hoptimator.linkedin.com condition met
--->%---
```
=> Wait for CRDs to be Established before using them in workflows

gradle/libs.versions.toml, hoptimator-cli/src/main/java/com/linkedin/hoptimator/HoptimatorCliApp.java, hoptimator-operator/build.gradle, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java
Added Apache Commons CLI to dependencies and used it to create the optional namespace argument for hoptimator-operator. While overkill for a singular flag, I'm expecting more flags will be added later, so a library for parsing arguments will make adding these much easier.
I manually tested with and without the -n/--namespace flag and it worked both times (i.e., the hoptimator-operator registered the namespace).
This PR addresses #17
=> Namespace arguments for hoptimator-operator

hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Resource.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/ResourceProvider.java, hoptimator-cli/src/main/java/com/linkedin/hoptimator/HoptimatorCliApp.java, hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/Pipeline.java, hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/PipelineRel.java
Added a new CLI command `!mermaid` which renders pipelines as mermaid flowcharts. In the resulting graph, resources are grouped by "kind".
Added a builder DSL to `ResourceProvider` to enable expressing source->sink relationships between resources. These relationships are not meaningful to the planner or operator.
The existing adapters are too simple to adequately test this against, so I modified the Kafka adapter to include additional "hops" (not included in the PR):
```
ResourceProvider.empty()
.with(x -> new MySqlTable(x))
.to(x -> new BrooklinCDC(x))
.to(x -> new KafkaTopic(x, numPartitions, topicConfigProvider.config(x)))
```
Using this somewhat contrived adapter, I tested a simple query across two tables:
```
0: hoptimator> !mermaid SELECT * FROM RAWKAFKA."products", …
```
=> Add !mermaid command

deploy/dev/rbac.yaml, deploy/hoptimator-operator-deployment.yaml, deploy/rbac.yaml, deploy/subscriptions.crd.yaml, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopic.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecClientConfigs.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecConfigMapRef.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Subscription.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionStatus.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/Operator.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Added logic to the subscription reconciler to keep track of deployed resources and to periodically check on their readiness. Subscription readiness is now predicated on the readiness of all resources in the pipeline.
Subscription status now progresses through multiple states:
```
$ kubectl get subscriptions -w
NAME       STATUS      DB         SQL
products               RAWKAFKA   SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
products   Planned.    RAWKAFKA   SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
products   Deployed.   RAWKAFKA   SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
products   Ready.      RAWKAFKA   SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
```
While the …
=> Report subscription status

hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Resource.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/ResourceTest.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionEnvironment.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Support `Resource.Environment` chains s.t. Resource templates can resolve variables from multiple places while enforcing an order of precedence.
Expose `Operator.properties()` to Resource templates via a root-level `Resource.Environment`. This enables users to pass arbitrary properties to the operator as command-line arguments, which are then visible within templates. Since these are exposed at the root-level (i.e. with lowest precedence), command-line properties will get masked by any other `Resource.Environment`s. For example, `pipeline.namespace` cannot be changed from the command-line, since the operator specifies this variable in an Environment with higher precedence.
We may consider reversing this behavior to give end-users more power, but for now we take the safer course.
New unit …
=> Support Environment chains

hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Resource.java, hoptimator-cli/src/main/java/com/linkedin/hoptimator/HoptimatorCliApp.java
Added new CLI command `!config`, enabling users to dynamically tweak configuration properties. These are then visible within templates, e.g. as rendered by the `!yaml` command.
Added a new constructor to `HoptimatorCliApp`, enabling client code to provide custom configuration.
Rendering YAML with the `!yaml` command may result in unexpanded variables, e.g. `{{pipeline.namespace}}`:
```
> !yaml insert into ...
--->%---
namespace: {{pipeline.namespace}}
--->%---
```
With the new `!config` command, we can specify these variables dynamically:
```
> !config pipeline.namespace=testing-123
> !yaml insert into ...
--->%---
namespace: testing-123
--->%---
```
=> Add CLI `!config` command

deploy/samples/subscriptions.yaml, etc/integration-tests.sql, hoptimator-kafka-adapter/src/main/resources/KafkaTopic.yaml.template, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Fix NPE when creating a Subscription without hints. Previously fixed by @HuiWang1020 but I broke it again :/
Added a second Subscription -- one with hints and one without -- to catch this in future.
=> Fix NPE again

.github/workflows/integration-tests.yml, deploy/samples/subscriptions.yaml, etc/cluster.yaml, etc/integration-tests.sql, hoptimator-flink-adapter/src/main/resources/SqlJob.yaml.template
For some reason the integration tests fail on GH when we try to run more than one Flink job. The integration tests pass locally, but on GH the KIND cluster seems to run out of resources. I tried a few things but will give up for now. Tracking in #46.
=> Drop second flink job

deploy/subscriptions.crd.yaml, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Acl.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpecResource.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopic.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecClientConfigs.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecConfigMapRef.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Subscription.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionStatus.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
It's not always possible to ensure that the SQL submitted with a Subscription will be implementable by the operator. In addition to syntax errors, it's possible that the user and operator disagree on what databases or tables exist, or which tables the user has access to. In such cases, the operator would just keep retrying and failing, without providing a reason to the user.
With this change, we report `.status.failed` anytime the operator is unable to implement a pipeline for the Subscription. In addition, we set `.status.message` to the offending exception. This gives the user some insight into why the Subscription is not being deployed successfully.
N.B. the operator will still backoff and retry failed Subscriptions, rather than give up entirely. In particular, a failed Subscription …
=> Report failed status

hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/KafkaTopic.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/KafkaTopicAcl.java, hoptimator-kafka-adapter/src/main/resources/KafkaTopic.yaml.template, hoptimator-kafka-adapter/src/main/resources/KafkaTopicAcl.yaml.template
The K8s API requires that object names and namespaces are all lowercase. The Kafka adapter was using the topic name as the object name, which K8s would reject if the topic has capital letters.
This fix uses a lowercased version of the topic name as the K8s object name.
This bug caused a deploy to get stuck in a testing environment. Hot-fixing this bug caused the deploy to get unstuck and succeed.
=> Bug fix: handle capitals in Kafka topics

hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/AvroConverter.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/builtin/DatagenSchemaFactory.java
Add support for BIGINT aka LONG.
When an input topic has a Long in the Avro schema, the resulting pipeline was trying to cast from Long down to Int, causing a ClassCastException within Flink (see below). This is because `AvroConverter` was essentially equating Ints and Longs, which works one way but not the other!
I added a BIGINT field to the built-in PERSON table. The existing integration tests should validate this now works.
Relevant stack trace:
```
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
at org.apache.flink.table.data.GenericRowData.getInt(GenericRowData.java:149)
at org.apache.flink.table.data.RowData.lambda$createFieldGetter$245ca7d1$6(RowData.java:245)
at org.apache.flink.table.data.RowData.lambda$createFieldGetter$25774257$1(RowD …
```
=> Support longs

Makefile, deploy/dev/kafka.yaml, etc/integration-tests.sql, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Names.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/Resource.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/ResourceTest.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/KafkaTopic.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/KafkaTopicAcl.java, hoptimator-kafka-adapter/src/main/resources/KafkaTopic.yaml.template, hoptimator-kafka-adapter/src/main/resources/KafkaTopicAcl.yaml.template, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Templates frequently need the same variable in different forms, e.g. `kafkaTopic` and `kafkaTopicLowerCase`. Rather than require `Resource`s to define multiple different formats of the same values, we now support simple transformations to be expressed in the templates themselves. This is similar to how Go/Helm templates allow transformation pipelines.
The following forms are added:
- `{{var toName}}`, `{{var:default toName}}`: canonicalize the variable as a valid K8s object name.
- `{{var toUpperCase}}`, `{{var:default toUpperCase}}`: render in all upper case.
- `{{var toLowerCase}}`, `{{var:default toLowerCase}}`: render in all lower case.
- `{{var concat}}`, `{{var:default concat}}`: concatinate a multiline string into one line
- `{{var concat toUpperCase}}`: apply both transformations …
=> Add support for transformations in resource templates

deploy/subscriptions.crd.yaml, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Acl.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpecResource.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopic.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecClientConfigs.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecConfigMapRef.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Subscription.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionStatus.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Closes #53.
The subscription operator now sets `.status.hints` after planning a pipeline, and re-plans the entire pipeline whenever `.status.hints` diverges from `.spec.hints`. This means that users can modify a Subscription's hints, and the changes will take effect. For example, a users can repartition an output Kafka topic by adjusting `.spec.hints.kafka.numPartitions`.
I edited an existing Subscription with `kubectl edit subs products` and added `.spec.hints.kafka.numPartitions = 16`. The operator reacts accordingly:
```
--->%---
Planning a new pipeline for Subscription/products with SQL `SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"`...
--->%---
Found existing topic products
--->%---
Desired partitions 16 > actual partitions 1. Creating additional …
```
=> Re-plan pipelines when hints change

deploy/subscriptions.crd.yaml, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/operator/kafka/KafkaTopicReconciler.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Acl.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclSpecResource.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1AclStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopic.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecClientConfigs.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicSpecConfigMapRef.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1KafkaTopicStatus.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1Subscription.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionList.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionSpec.java, hoptimator-models/src/main/java/com/linkedin/hoptimator/models/V1alpha1SubscriptionStatus.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
The subscription controller now gathers "attributes" from downstream resources and reports them as `.status.attributes`. These attributes are open-ended and depend on the various downstream controllers, but currently include `jobId`, `numPartitions`, `startTime`, and more, as reported by the Kafka topic controller and Flink operator.
The Kafka topic controller now reports the actual number of partitions, which may diverge from the `kafka.numPartitions` hint. This means users can request a specific number of partitions with `.spec.hints.kafka.numPartitions` and then check `.status.attributes.numPartitions` to see the actual number of partitions.
Attributes are collected from downstream resources and the job, not from upstream/input resources. For example, `numPartitions` would refer to an …
=> Gather attributes of downstream resources

hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/AvroConverter.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/DataType.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/ScriptImplementor.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/TableResolver.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/AvroConverterTest.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/DataTypeTest.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/ScriptImplementorTest.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/RawKafkaSchemaFactory.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java, hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/PipelineRel.java
`TableResolver` and `DataType.Struct` can now optionally skip nested `Row`s. This is useful for pipelines that can't handle complex record types.
`ScriptImplementor` will now replace explicit `Row(...)` constructors with implicit `(...)` row constructors, which is better supported by Flink before 1.18.
Added support for Avro arrays.
Small bug fixes related to nullability of Avro fields.
Added `dropNestedRows` method to `DataType.Struct`. Added `mapStruct` method to `TableResolver` to enable applying this and similar data type transformations to rows. Adapters can use this as an easy way to deal with complex schemas.
Flink SQL prior to 1.18 doesn't support arbitrary expressions inside an explicit row constructor, so we now rewrite these using an implicit row constructor. This works when …
=> Use implicit row constructors. Optionally skip nested rows. Nullability bug fixes.

hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/subscription/SubscriptionReconciler.java
Added optional filter predicate to subscription reconciler.
One way to serve multiple use-cases is to run Hoptimator in multiple namespaces, each with different configurations. However, this proves unwieldy in practice, because each namespace has its own operational overhead (e.g. RBAC policies). Instead, it is convenient to have Hoptimator partition a single namespace based on its own criteria (e.g. subscription prefix). 
To that end, we add support for filtering Subscriptions. This enables an operator to spin up multiple Subscription controllers, each with different filters and different configurations -- all in the same namespace. For example, an operator may want to treat Subscriptions differently if they have a `-staging` or `-prod` suffix.
Tested in downstream project.
=> Add optional filter to subscription reconciler

deploy/samples/subscriptions.yaml, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/DataType.java, hoptimator-catalog/src/main/java/com/linkedin/hoptimator/catalog/ScriptImplementor.java, hoptimator-catalog/src/test/java/com/linkedin/hoptimator/catalog/ScriptImplementorTest.java, hoptimator-kafka-adapter/src/main/java/com/linkedin/hoptimator/catalog/kafka/RawKafkaSchemaFactory.java, hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/PipelineRel.java
Drop NULL columns (e.g. `NULL AS KEY`) from INSERT INTO pipelines.
Promote NULL fields to BYTES in DDL (e.g. `KEY BYTES`).
Flink does not allow NULLs in queries (SQL) or in table definitions (DDL). This is problematic, because we would like to be able to write `NULL AS KEY` in subscriptions.
In Hoptimator, sink tables are _derived_ from subscription SQL. If we write `NULL AS KEY` in a subscription, the sink table would have a `NULL`-typed column, and the Flink job would fail. Instead, `NULL AS KEY` should result in the column being omitted form the pipeline entirely (defaulting to NULL).
At the same time, Flink DDL cannot have NULL-typed fields, so we promote these to BYTES.
The result is that `SELECT ... NULL AS KEY ...` results in a sink table with `KEY BYTES` and pipelines that omit …
=> Drop NULL columns from INSERT INTO

deploy/dev/kafka.yaml, deploy/hoptimator-operator-deployment.yaml, hoptimator-cli/src/main/java/com/linkedin/hoptimator/HoptimatorCliApp.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java, hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/HoptimatorPlanner.java
Support loading the catalog via JDBC urls.
Support loading the catalog from a Calcite Schema.
Previously, we required a Calcite model file (e.g. `model.yaml`) to load the catalog. We still support this, but now we expect to load model files via the url `jdbc:calcite:model=...`. In addition, any JDBC url theoretically works (tho the catalog thus loaded may not be useful).
Looking ahead, we plan to restructure the Catalog API to enable the use of arbitrary JDBC drivers. Today, we only support catalogs specifically written for Hoptimator.
Existing integration tests should pass.
=> Load from JDBC

bin/hoptimator, hoptimator-k8s/build.gradle
JFrog failed internally to pull a new version of hoptimator-operator because it couldn't find hoptimator-k8s
Also remove broken bin/ script since `hoptimator-cli-integration` no longer exists
=> Add publishing for hoptimator-k8s

hoptimator-jdbc/build.gradle
Right now we are only publishing hoptimator-jdbc-driver as a fat jar bundling dependencies needed for the CLI. We are getting failures promoting several packages because hoptimator-jdbc by itself is missing, which is depended upon by hoptimator-k8s
=> Publish hoptimator-jdbc

deploy/samples/venicedb.yaml, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sConnector.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sJobDeployer.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sSourceDeployer.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/Template.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRel.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/TestTemplate.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/planner/TestPipelineRel.java
- Support Primitive Venice Keys
- Add Template option for empty string defaults
- Add template & key option testing
Global templates were causing problems with keys getting overwritten, see example below:
Without change:
```
0: Hoptimator> !pipeline insert into "VENICE-CLUSTER0"."test-store" ("KEY$id", "intField") select "KEY", "intField" from "VENICE-CLUSTER0"."test-store-primitive"
CREATE TABLE IF NOT EXISTS `test-store-primitive` (`intField` INTEGER, `stringField` VARCHAR, `KEY` INTEGER) WITH ('connector'='venice', 'key.fields'='KEY_id', 'key.fields-prefix'='KEY_', 'key.type'='RECORD', 'partial-update-mode'='true', 'storeName'='test-store-primitive', 'value.fields-include'='EXCEPT_KEY');
CREATE TABLE IF NOT EXISTS `test-store` (`intField` INTEGER, `stringField` VARCHAR, `KEY_id` …
```
=> Support Venice Primitive keys

.github/workflows/integration-tests.yml, Dockerfile, Makefile, README.md, deploy/dev/kafka.yaml, deploy/dev/rbac.yaml, deploy/docker/venice/docker-compose-single-dc-setup.yaml, deploy/rbac.yaml, deploy/samples/flinkDeployment.yaml, deploy/samples/kafkadb.yaml, etc/cluster.yaml, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sContext.java, hoptimator-kafka/src/test/resources/kafka-ddl.id, hoptimator-operator-integration/build.gradle, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/PipelineOperatorApp.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/ScriptImplementor.java, hoptimator-venice/src/test/resources/venice-ddl-insert-all.id, hoptimator-venice/src/test/resources/venice-ddl-insert-partial.id, hoptimator-venice/src/test/resources/venice-ddl-select.id
- Fixed issue with FLINK SQL syntax where query table: `KAFKA`.`existing-topic-2` should have just been `existing-topic-2`.
- Got deployment of Flink jobs working through Flink deployment cluster
- Updated Flink connector options in `kafkadb.yaml` to the minimum required set needed to pass through to Flink
- Needed to change Kafka connection mechanism. Connection on the command line using the forwarded port 9092 works via localhost to the 'external' strimzi cluster. However, this doesn't work for k8s pod to pod communication (Flink deployment pod -> Kafka cluster), pod connections need to use the 'internal' strimzi connection mechanisms `one-kafka-bootstrap.kafka.svc.cluster.local:9094`.
- Integration tests has apparently always been failing but were incorrectly showing as passing due to …
=> Fix various issues with SQL generation, flink job routing, integration-tests

Makefile, deploy/docker/zeppelin/Dockerfile-zeppelin, deploy/docker/zeppelin/interpreter.json, deploy/docker/zeppelin/zeppelin-site.xml, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sContext.java
Adds Zeppelin configured for use with Hopitmator. Includes new make targets: `build-zeppelin` and `run-zeppelin`.
* Modifies Kubernetes config resolution. 
* Uses environment overrides to replace config values.
* Adds `shadowJar` to `make install`
* Sets default interpreter as Hoptimator.
* Removes all other non-jdbc connectors.
* Connects to local K8s services.
steps:
```
$ make build-zeppelin
$ make run-zeppelin
```
open browser: [localhost:8080](http://localhost:8080)
create: 
query:
=> Add Zeppelin

hoptimator-kafka/src/test/resources/kafka-ddl.id, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRel.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/ScriptImplementor.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/TestDataTypeUtils.java, hoptimator-venice/src/test/resources/venice-ddl-insert-all.id, hoptimator-venice/src/test/resources/venice-ddl-insert-partial.id, hoptimator-venice/src/test/resources/venice-ddl-select.id
- Added `CREATE DATABASE` statements to generated SQL
- Added schema name to `CREATE TABLE` and `INSERT INTO` SQL
- Dropped extraneous logic unflattening logic
The old planner generated `CREATE IF NOT EXISTS DATABASE` statements along with `CREATE IF NOT EXISTS TABLE` statements, allowing tables to be referenced as `<schema>.<table>`. I had dropped this logic in the new version of the planner, but it ends up being useful. Without fully-qualified table names, it becomes difficult to distinguish between tables, fields, and `t1.foo` field aliases in generated SQL. In particular, joins across tables with the same field name where incorrectly being rewritten like `foo = foo`, instead of `t1.foo = t2.foo`.
Integration tests pass with and without the Flink engine installed.
Manually tested a …
=> Fix compound identifier bug

hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRel.java
`RelOptUtil.equal` effectively calls `areRowTypesEqual` under the hood. With the change in #94 this check is no longer valid because the `query` types are always going to be a subset of the `sink` types now. We can probably add some validation to assert this but this check is no longer enough as is.
=> Remove assert

deploy/samples/kafkadb.yaml, deploy/samples/venicedb.yaml, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/BuiltinCatalogProvider.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorConnection.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDdlExecutor.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sCatalog.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sContext.java, hoptimator-kafka/src/test/resources/kafka-ddl.id, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/ConfigService.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/ScriptImplementor.java
Fix case statements causing a null pointer exception
Example query:
```
create or replace materialized view ADS."AD_CLICKS$test1" AS SELECT company_name, CASE WHEN company_urn = 'PUBLISHED' THEN NULL ELSE company_urn END FROM PROFILE.COMPANIES;
```
Result:
```
- CREATE DATABASE IF NOT EXISTS `PROFILE` WITH ();
- CREATE TABLE IF NOT EXISTS `PROFILE`.`COMPANIES` (`COMPANY_NAME` VARCHAR, `COMPANY_URN` VARCHAR) WITH ('connector'='datagen', 'number-of-rows'='10');
- CREATE DATABASE IF NOT EXISTS `ADS` WITH ();
- CREATE TABLE IF NOT EXISTS `ADS`.`AD_CLICKS` (`CAMPAIGN_URN` VARCHAR, `MEMBER_URN` VARCHAR) WITH ('connector'='blackhole');
- INSERT INTO `ADS`.`AD_CLICKS` (`COMPANY_NAME`, `EXPR_1`) SELECT `COMPANY_NAME`, CASE WHEN `COMPANY_URN` = 'PUBLISHED' THEN NULL ELSE `COMPANY_URN` END FROM …
```
=> Fix case statement exception

hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDriver.java, hoptimator-jdbc/src/testFixtures/java/com/linkedin/hoptimator/jdbc/QuidemTestBase.java, hoptimator-kafka/src/main/java/com/linkedin/hoptimator/kafka/KafkaDriver.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/ConfigService.java, hoptimator-venice/src/main/java/com/linkedin/hoptimator/venice/VeniceDriver.java
- Do not load JDBC driver configuration from `ConfigService`. Instead, rely on connection properties.
- Add `catalogs` connection property to limit loaded catalogs.
- Properly load connection properties from JDBC URL or via `getConnection()` argument.
Previously, `ConfigService` was used within various plugins (e.g. JDBC drivers) to load dynamic configuration. Some of these cases are now obviated by #99's connection properties, which thread through to each plugin, _except_ JDBC drivers. For JDBC drivers, we prefer to use their respective URL, when possible, since relying on `ConfigService` may involve dynamically fetching configurations (e.g. ConfigMaps) when loading each database.
In addition, we will want to support a `CREATE DATABASE` eventually, which won't be able to provide the …
=> Simplify config loading

hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDriver.java, hoptimator-kafka/src/main/java/com/linkedin/hoptimator/kafka/KafkaDriver.java, hoptimator-venice/src/main/java/com/linkedin/hoptimator/venice/VeniceDriver.java
Change config loading order in JDBC drivers to consistently give URL properties precedence over `getConnection()`'s properties.
JDBC drivers may be loaded via the older `DriverManager` mechanism or via the newer `DataSource` mechanism. With the former, drivers may be loaded as `getConnection(url, props)`, where `props` are optional connection properties. The URL itself very often includes connection properties, raising the question of which source of properties takes precdence.
The JDBC docs do not specify what should happen here, explicitly leaving it to the drivers to decide.
Given that end users can often _only_ control and see the URL, we think it makes sense to given the URL precedence here. In that case, the `props` supplied to `getConnection()` should be considered defaults rather …
=> Change config loading order to give URLs precedence

Makefile, deploy/docker/zeppelin/Dockerfile-zeppelin, deploy/docker/zeppelin/interpreter.json, deploy/docker/zeppelin/zeppelin-flink-engine.yaml
Likely will need to make similar new yaml files to get Kafka & Venice working through Zeppelin, will add separately if needed
=> Fix Zeppelin k8s connection

hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/HoptimatorOperatorApp.java
Watch namspace != the namespace we want to connect to. Removing this will default the operator pod to use environment variable: `POD_NAMESPACE_FILEPATH`
=> Remove incorrect operator namespace

hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sApi.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/PipelineOperatorApp.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/pipeline/PipelineReconciler.java
Fix pipeline reconciler namespacing.
Similar issues as prior where there is a difference with the namespace to watch vs to connect to. And when reconciling a request, we need to make sure to use that objects namespace
=> Fix pipeline reconciler

Makefile, deploy/dev/kafka.yaml, deploy/docker/zeppelin/zeppelin-kafkadb.yaml, deploy/rbac.yaml, deploy/samples/kafkadb.yaml, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDriver.java, hoptimator-kafka/src/test/resources/kafka-ddl.id
- Connection properties were not being loaded all the way through properly
- Kafka bootstrapUrl needed to be changed to work within docker
- Noticed some rbac discrepancies
- Needed to add "key.format" for flink kafka to work
- Left in a TODO around kafka broker advertised ports. Tried adding a new broker and a new listener, haven't gotten it to work yet.
=> Apply some Zeppelin fixes for kafka

hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sMetadata.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sPipelineTable.java
- Add k8s.PIPELINES metadata table.
So far, this is just for convenience purposes, and for symmetry with the other metadata tables. With this change, users can check on the status of their pipelines without dropping out of the CLI.
```
0: Hoptimator> select * from "k8s".pipelines;
+---------------+-----------+
|     NAME      |  STATUS   |
+---------------+-----------+
| ads-audience2 | Deployed. |
| ads-target2   | Deployed. |
+---------------+-----------+
2 rows selected (0.593 seconds)
```
=> Add PIPELINES metadata table

deploy/samples/demodb.yaml, hoptimator, hoptimator-demodb/src/main/java/com/linkedin/hoptimator/demodb/DemoDriver.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDdlExecutor.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/MaterializedViewTable.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/schema/HoptimatorViewTableMacro.java, hoptimator-jdbc/src/testFixtures/java/com/linkedin/hoptimator/jdbc/QuidemTestBase.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sCatalog.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sDatabaseTable.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sViewTable.java, hoptimator-k8s/src/test/java/com/linkedin/hoptimator/k8s/TestSqlScripts.java, hoptimator-k8s/src/test/resources/k8s-ddl-function.id, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/RemoteToEnumerableConverterRule.java
Fixes a few issues:
- Make demodb consistent in using key/value pair for jdbc connection
- Introduce HoptimatorViewTableMacro, this is strictly to work around the static connection object Calcite uses for materialized views (don't really get why they do this): https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/schema/impl/MaterializedViewTable.java#L58
- Add property support for quidem testing
- Update K8sDatabaseTable/K8sViewTable to also pass through connection properties
=> Fix connection pass through preventing functions from working

Makefile, hoptimator-k8s/src/test/resources/k8s-ddl-function.id, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRules.java
SQL functions were still not fully working with #112. The tests were only testing views, creation of materialized views, when walking the implementor path, uncovered a few issues.
- Added `LogicAggregate` rule to support LISTAGG
- Added `Uncollect` rule to support UNNEST
There are still feature gaps present
```
create or replace view ADS."unnested" AS SELECT * FROM UNNEST(ARRAY(SELECT "FIRST_NAME" FROM profile.members)) AS name;
```
This still fails expected rules for `Collect` and `LogicalValues`. Hit a roadblock with `Collect` which is missing `RelToSqlConverter` conversion so gave up on that for now.
=> Add missing rules for LISTAGG & UNNEST

hoptimator-util/src/main/java/com/linkedin/hoptimator/util/DeploymentService.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/DeploymentServiceTest.java
Validate contents of `Properties` object used for "hints". This is related to an issue (error below) reported by clients after deploying #117. The expected use of the "hints" and "pipeline" options are unchanged. The unit test validate the following conditions:
1. An empty "hints" map is ignored.
1. Non-empty "hints" are valid as either key value pairs **or** flags.
1. Parsing of "pipeline" occurs regardless of "hints" (no collision detection).
----
The input `Properties` parameter for `parseHints` included a "hints" key with an empty value.
```
Caused by: java.lang.IllegalArgumentException: Chunk [] is not a valid entry
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[com.google.guava.guava-33.3.1-jre.jar:?]
at …
```
=> Remove invalid hints from Properties inputs.

Makefile, hoptimator-flink-runner/Dockerfile-flink-operator, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/DataTypeUtils.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/ScriptImplementor.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/DeploymentServiceTest.java, hoptimator-util/src/test/java/com/linkedin/hoptimator/util/TestDataTypeUtils.java
#95 was responsible for handling arrays of several types and arrays of row types however there was a gap supporting arrays of arrays i.e. `Array<Array<Varchar>`
This change handles support for any number of nested arrays. Nested arrays are "flattened" into separate types for each level and are reconstructed when unflattened back into the nested type
=> Support nested arrays

hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sApi.java
There was a bug if you recreate the same materialized view, the pipeline ownership to the view was getting thrown out.
```
0: Hoptimator> create or replace materialized view venice."test-store$my-view4" as select "KEY" as "KEY_id", "VALUE" as "stringField" from kafka."existing-topic-1";
No rows affected (1.9 seconds)
kind: Pipeline
metadata:
creationTimestamp: "2025-03-17T21:34:56Z"
generation: 1
name: venice-test-store-my-view4
namespace: default
ownerReferences:
- apiVersion: hoptimator.linkedin.com/v1alpha1
kind: View
name: venice-test-store-my-view4
uid: 80db4704-02a8-4a5f-af63-8167ea2b213a
```
=> Fix pipeline ownership on update

hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRel.java
Adds validation for column names when doing a partial view (i.e. view on table that already exists).
Tests:
- New view, column names don't matter, no validation done
```
0: Hoptimator> create or replace materialized view venice."new-view" as select "KEY" as "KEY_id", "VALUE" as stringField from kafka."existing-topic-1";
No rows affected (0.517 seconds)
```
- Valid column names for partial view
```
0: Hoptimator> create or replace materialized view venice."test-store$my-view" as select "KEY" as "KEY_id", "VALUE" as "stringField" from kafka."existing-topic-1";
No rows affected (1.684 seconds)
```
- Invalid column name for partial view
```
0: Hoptimator> create or replace materialized view venice."test-store$my-view" as select "KEY" as "KEY_id", "VALUE" as stringField from …
```
=> Assert column names for partial views

hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sApi.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sYamlApi.java
Will log when we modify K8s object:
Ex: `Created K8s obj: View:venice-test-store-my-view`
=> Add logging for deployers

hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/HoptimatorPlanner.java
Simplifies a lot of code internally to support loading the model file from resources. This will eventually be deprecated anyway.
=> Add support to load model file from resources

hoptimator-avro/src/main/java/com/linkedin/hoptimator/avro/AvroConverter.java
Unions of several types are flattened into a structured type when we create an Avro schema. These fields need to be nullable inside of this type. We already handle complex arrays in this manner, was just missing for unions.
Below describes the before & after for this change, fields are obfuscated from the actual schemas.
Before change:
```
!specify INSERT INTO venice."my_store" ("KEY", "arrayField") SELECT CASE WHEN "union"['type1']['keyField'] IS NOT NULL THEN "union"['type1]['keyField'] ELSE "event"['type2']['keyField'] END AS "KEY", CASE WHEN "union"['type1']['arrayField'] IS NOT NULL THEN "union"['type1']['arrayField'] ELSE "union"['type2']['arrayField'] END AS "arrayField" FROM "kafka"."my_topic"
...
- CREATE DATABASE IF NOT EXISTS `KAFKA` WITH ();
- CREATE TABLE IF NOT EXISTS …
```
=> Fix issue with complex union avro record

README.md, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sConnector.java, hoptimator-kafka/src/test/java/com/linkedin/hoptimator/kafka/TestSqlScripts.java, hoptimator-kafka/src/test/resources/kafka-ddl.id, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/Template.java
Supports automatic connector hint passthrough without the need for templates.
Format is expected as `<engine-connector-name>.<source|sink>.<connectorConfigName>`
See README for more information
Also fixed a bug when applying sqljob yaml for configs where it would complain about ints or booleans because it wasn't surrounded in single quotes.
=> Support connector hint passthrough

hoptimator-demodb/src/main/java/com/linkedin/hoptimator/demodb/DemoDriver.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDdlExecutor.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDriver.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/ValidationService.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sApi.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sConnector.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sUtils.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/K8sYamlApi.java, hoptimator-kafka/src/main/java/com/linkedin/hoptimator/kafka/KafkaDriver.java, hoptimator-util/src/main/java/com/linkedin/hoptimator/util/planner/PipelineRel.java, hoptimator-venice/src/main/java/com/linkedin/hoptimator/venice/VeniceDriver.java
- Throw `SQLNonTransientException` (or derivative) for validation errors, etc.
- Throw `SQLTransientConnectionException` for IO errors encountered when loading the catalog, etc.
Calcite frequently uses unchecked exceptions, and Hoptimator follows that pattern where necessary. Unfortunately, this means client code often receives opaque `RuntimeException`s. Where possible, we want to instead throw `SQL[Non]TransientException`, s.t. client code can decide whether to retry or surface an error to users.
None. Client code will be tested externally.
N.B. we don't expect 100% coverage wrt this transient-vs-non-transient distinction at this point. As future `RuntimeException`s are encountered, we may need to revisit this problem.
=> Add retriable/transient exceptions

Makefile, README.md
- Remove deploy-samples target
- Add deploy-demo target
- Add set up steps to README
=> Address gaps in readme & make targets

hoptimator-k8s/build.gradle, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/status/K8sPipelineElementStatus.java, hoptimator-k8s/src/main/java/com/linkedin/hoptimator/k8s/status/K8sPipelineElementStatusEstimator.java, hoptimator-k8s/src/test/java/com/linkedin/hoptimator/k8s/status/K8sPipelineElementStatusEstimatorTest.java, hoptimator-operator/src/main/java/com/linkedin/hoptimator/operator/pipeline/PipelineReconciler.java
We would like to expose statues of pipeline and its elements as new K8s metadata status tables.
This PR is to refactor the common status estimating logic to be reused in another PR - see:
https://github.com/linkedin/Hoptimator/tree/trung/status-table
- K8sPipelineElementStatusEstimatorTest
- Created a new pipeline in hoptimator and verified logs in hoptimator-operator-deployment pod
=> Refactor status prediction logic in PipelineReconciler to a common package

hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorConnection.java, hoptimator-jdbc/src/test/java/com/linkedin/hoptimator/jdbc/JdbcTestBase.java, hoptimator-jdbc/src/test/java/com/linkedin/hoptimator/jdbc/TestBasicSql.java
There is no support for PreparedStatement in the hoptimator-jdbc yet, thus its clients would face SQL injection attack risk if allowing queries with parameters.
This PR is to add another option to send SQL statements with many advantages, particularly preventing SQL injection attacks: https://docs.oracle.com/javase/tutorial/jdbc/basics/prepared.html
- Unit test: add query using PreparedStatement to com.linkedin.hoptimator.jdbc.TestBasicSql.insertIntoSelectFrom()
- Local integration test: queried "k8s" metadata tables using java client with PreparedStatement created by HoptimatorConnection and verified that the returned ResultSet is as expected.
=> Add support of java.sql.PreparedStatement to HoptimatorConnection

hoptimator-avro/src/main/java/com/linkedin/hoptimator/avro/AvroConverter.java, hoptimator-avro/src/test/java/com/linkedin/hoptimator/avro/AvroConverterTest.java
- Fix `Nested union: ["null",["null"]]` bug
Avro does not allow `["null",["null"]]` nor `["null", "null"]`. `AvroConverter` was generating `["null",["null"]]`, presumably in an attempt to represent a nullable null type. But of course the null type is implicitly nullable anyway.
New unit test fails with `Nested union: ["null",["null"]]` without the fix. Passes with the fix.
=> Fix mishandling of null types in output Avro schemas

hoptimator-cli/src/main/java/sqlline/HoptimatorAppConfig.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorConnection.java
Expands #151 to add source/sink configs to the resolve output
If a given source or sink is not applicable an empty set of configs `{}` will be given.
```
0: Hoptimator> !resolve ADS.AD_CLICKS
Avro schema:
{
"type" : "record",
"name" : "ad_clicks",
"namespace" : "com.linkedin.ads",
"doc" : "RecordType(VARCHAR CAMPAIGN_URN, VARCHAR MEMBER_URN)",
"fields" : [ {
"name" : "CAMPAIGN_URN",
"type" : [ "null", "string" ],
"doc" : "CAMPAIGN_URN VARCHAR"
}, {
"name" : "MEMBER_URN",
"type" : [ "null", "string" ],
"doc" : "MEMBER_URN VARCHAR"
} ]
}
Source configs:
{connector=datagen, number-of-rows=10}
Sink configs:
{connector=blackhole}
0: Hoptimator> !resolve KAFKA.existing-topic-1
Avro schema:
{
"type" : "record",
"name" : "existingtopic1",
"namespace" : "com.linkedin.kafka",
"doc" : …
```
=> Add source/sink configs to resolve output

hoptimator-avro/src/main/java/com/linkedin/hoptimator/avro/AvroConverter.java
When a schema with multiple Array of Structs is converted, AvroConverter runs into a error "arrayElement can't be redefined", This PR fixes the issue by adding the name of the struct as prefix to make the record names unique
=> Fix AvroConverter when multiple Array of Struct schemas is converted

hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorConnection.java, hoptimator-jdbc/src/main/java/com/linkedin/hoptimator/jdbc/HoptimatorDdlExecutor.java, hoptimator-jdbc/src/test/java/com/linkedin/hoptimator/jdbc/JdbcTestBase.java, hoptimator-jdbc/src/test/java/com/linkedin/hoptimator/jdbc/TestBasicSql.java
**Problem:**
Currently Hoptimator jdbc doesn't provide execution details such as validations or deployment steps other than the number of modified rows. Some clients are interested in those details to help users understand what happen behind the scene.
**Solution:**
This PR add logging function to HoptimatorConnection for create (materialized) view statements so its clients can retrieve logs at HoptimatorDdlExecutor level by registering hooks. It has a pending TODO to add statement execution log isolation in the future.
Logging at lower level than the HoptimatorDdlExecutor could be added in another PR if desired.
With this PR, when executing "create materialized view \"QUEUING\".test_view_00 as select * from \"QUEUING\".\"test-source\"" statement, hoptimator client would get the following …
=> Add logging function to HoptimatorConnection so its clients can retrieve logs by registering hooks

README.md, hoptimator-mcp-server-app/build.gradle, hoptimator-mcp-server/build.gradle, settings.gradle, start-mcp-server
Split mcp package to remove oss drivers. Wasn't very extensible as written.
Tested no regressions in mcp server
=> Split mcp package to remove oss drivers

hoptimator-avro/src/main/java/com/linkedin/hoptimator/avro/AvroConverter.java, hoptimator-avro/src/test/java/com/linkedin/hoptimator/avro/AvroConverterTest.java
The !resolve endpoint attempts to pretty print the avro schema. At print time certain validations are made that fields are not redefined. In our current logic we were always using the same namespace but it is often the case where fields with the same name can exist under separate namespaces, with different record schemas.
This fix always assumes different namespaces for different record fields. It keeps the schema verbose but will solve any collision problems. Execution engines shouldn't actually care about the namespace
Also fixes an issue where there was no namespace attached to map and array fields.
=> Fix resolve error caused by avro record collision
